"""Sync schema

Revision ID: 5c50fc6bc3de
Revises: 
Create Date: 2026-01-12 09:47:13.131930

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5c50fc6bc3de'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('whatsapp_config')
    op.drop_index(op.f('ix_qrcodes_id'), table_name='qrcodes')
    op.drop_table('qrcodes')
    op.drop_table('whatsapp_logs')
    op.drop_index(op.f('ix_whatsapp_instances_id'), table_name='whatsapp_instances')
    op.drop_index(op.f('ix_whatsapp_instances_instance_key'), table_name='whatsapp_instances')
    op.drop_table('whatsapp_instances')
    op.drop_index(op.f('ix_fila_envio_id'), table_name='fila_envio')
    op.drop_table('fila_envio')
    op.drop_index(op.f('ix_maintenance_settings_id'), table_name='maintenance_settings')
    op.drop_table('maintenance_settings')
    op.drop_index(op.f('ix_bot_usage_history_id'), table_name='bot_usage_history')
    op.drop_table('bot_usage_history')
    op.drop_index(op.f('ix_bot_status_id'), table_name='bot_status')
    op.drop_table('bot_status')
    op.drop_index(op.f('idx_queue_schedule'), table_name='whatsapp_queue')
    op.drop_index(op.f('idx_queue_status'), table_name='whatsapp_queue')
    op.drop_table('whatsapp_queue')
    op.drop_index(op.f('ix_messages_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_bot_config_id'), table_name='bot_config')
    op.drop_table('bot_config')
    op.add_column('system_settings', sa.Column('phone_whatsapp', sa.String(), nullable=True))
    op.add_column('system_settings', sa.Column('pix_key', sa.String(), nullable=True))
    op.add_column('users', sa.Column('estado_civil', sa.String(), nullable=True))
    op.add_column('users', sa.Column('profissao', sa.String(), nullable=True))
    op.drop_column('users', 'pix_name')
    op.drop_column('users', 'pix_city')
    op.drop_column('users', 'pix_key')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('pix_key', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('pix_city', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('pix_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('users', 'profissao')
    op.drop_column('users', 'estado_civil')
    op.drop_column('system_settings', 'pix_key')
    op.drop_column('system_settings', 'phone_whatsapp')
    op.create_table('bot_config',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('bot_nome', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('min_delay', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('max_delay', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('hora_inicio', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('hora_fim', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('ativo', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('bot_config_pkey'))
    )
    op.create_index(op.f('ix_bot_config_id'), 'bot_config', ['id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('instance_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('external_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('sender_number', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('receiver_number', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('direction', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['instance_id'], ['whatsapp_instances.id'], name=op.f('messages_instance_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('messages_pkey'))
    )
    op.create_index(op.f('ix_messages_id'), 'messages', ['id'], unique=False)
    op.create_table('whatsapp_queue',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('phone_number', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('message_body', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('media_url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('media_type', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('status', sa.TEXT(), server_default=sa.text("'pending'::text"), autoincrement=False, nullable=True),
    sa.Column('attempts', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('last_error', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('scheduled_for', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('processed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('whatsapp_queue_pkey'))
    )
    op.create_index(op.f('idx_queue_status'), 'whatsapp_queue', ['status'], unique=False)
    op.create_index(op.f('idx_queue_schedule'), 'whatsapp_queue', ['scheduled_for'], unique=False)
    op.create_table('bot_status',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('status_conexao', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('qr_code_base64', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('ultima_atualizacao', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('bot_status_pkey'))
    )
    op.create_index(op.f('ix_bot_status_id'), 'bot_status', ['id'], unique=False)
    op.create_table('bot_usage_history',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('action_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('typing_duration', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('wait_duration', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('metadata_json', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('bot_usage_history_pkey'))
    )
    op.create_index(op.f('ix_bot_usage_history_id'), 'bot_usage_history', ['id'], unique=False)
    op.create_table('maintenance_settings',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('days_before', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('template_msg', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('last_run', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('default_interval_months', sa.INTEGER(), server_default=sa.text('6'), autoincrement=False, nullable=True),
    sa.Column('template_msg_first_time', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('maintenance_settings_pkey'))
    )
    op.create_index(op.f('ix_maintenance_settings_id'), 'maintenance_settings', ['id'], unique=False)
    op.create_table('fila_envio',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('numero', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('mensagem', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('media_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('erro_log', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('enviado_em', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('scheduled_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('fila_envio_pkey'))
    )
    op.create_index(op.f('ix_fila_envio_id'), 'fila_envio', ['id'], unique=False)
    op.create_table('whatsapp_instances',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('instance_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('instance_key', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('qrcode_base64', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('whatsapp_instances_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('whatsapp_instances_pkey'))
    )
    op.create_index(op.f('ix_whatsapp_instances_instance_key'), 'whatsapp_instances', ['instance_key'], unique=True)
    op.create_index(op.f('ix_whatsapp_instances_id'), 'whatsapp_instances', ['id'], unique=False)
    op.create_table('whatsapp_logs',
    sa.Column('id', sa.BIGINT(), sa.Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('level', sa.TEXT(), server_default=sa.text("'info'::text"), autoincrement=False, nullable=True),
    sa.Column('event', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('whatsapp_logs_pkey'))
    )
    op.create_table('qrcodes',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('tipo', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('destino', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('cor', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('logo_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('qrcodes_pkey'))
    )
    op.create_index(op.f('ix_qrcodes_id'), 'qrcodes', ['id'], unique=False)
    op.create_table('whatsapp_config',
    sa.Column('id', sa.BIGINT(), sa.Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('instance_name', sa.TEXT(), server_default=sa.text("'default'::text"), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.Column('sleep_start_hour', sa.INTEGER(), server_default=sa.text('22'), autoincrement=False, nullable=True),
    sa.Column('sleep_end_hour', sa.INTEGER(), server_default=sa.text('8'), autoincrement=False, nullable=True),
    sa.Column('min_delay_seconds', sa.INTEGER(), server_default=sa.text('10'), autoincrement=False, nullable=True),
    sa.Column('max_delay_seconds', sa.INTEGER(), server_default=sa.text('25'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('whatsapp_config_pkey'))
    )
    # ### end Alembic commands ###
